[package]
name = "sql-builder"
version = "0.1.0"
description = "Simple SQL code generator."
authors = ["perdumonocle <konstantin_1987@mail.ru>"]
license = "MIT"
edition = "2018"
keywords = ["sql", "db", "database", "builder", "simple"]

[dependencies]
