[package]
name = "sql-builder"
version = "0.1.2"
description = "Simple SQL code generator."
authors = ["perdumonocle <konstantin_1987@mail.ru>"]
license = "MIT"
edition = "2018"
keywords = ["sql", "db", "database", "simple", "codegen"]
repository = "https://github.com/perdumonocle/sql-builder.git"

[dependencies]
